### PR TITLE
Adding Dad Jokes

### PR DESCRIPTION
**Pull request by AustinCasteel**

### CODE REVIEW

**Review by aaronchantrill — CHANGES_REQUESTED** [review]
To test, add this line to profile.yml:
```
plugin_repositories:
    https://raw.githubusercontent.com/AustinCasteel/naomi-plugins/Adding-DadJokes-Plugin/plugins.csv: Enabled
```
Installing worked fine:
```
$ Naomi --install "Dad Jokes"

      ___           ___           ___           ___                  
     /\__\         /\  \         /\  \         /\__\          ___    
    /::|  |       /::\  \       /::\  \       /::|  |        /\  \   
   /:|:|  |      /:/\:\  \     /:/\:\  \     /:|:|  |        \:\  \  
  /:/|:|  |__   /::\~\:\  \   /:/  \:\  \   /:/|:|__|__      /::\__\ 
 /:/ |:| /\__\ /:/\:\ \:\__\ /:/__/ \:\__\ /:/ |::::\__\  __/:/\/__/ 
 \/__|:|/:/  / \/__\:\/:/  / \:\  \ /:/  / \/__/~~/:/  / /\/:/  /    
     |:/:/  /       \::/  /   \:\  /:/  /        /:/  /  \::/__/     
     |::/  /        /:/  /     \:\/:/  /        /:/  /    \:\__\     
     /:/  /        /:/  /       \::/  /        /:/  /      \/__/     
     \/__/         \/__/         \/__/         \/__/                 

Installing Dad Jokes...
Plugin "Dad Jokes" is enabled
Plugin "Dad Jokes" installed to /home/pi/.config/naomi/plugins/speechhandler/Dad_Jokes
```
However, I'm getting the following error when I activate the plugin:
```
>> My name is MAGICVOICE.                                                                                                                                              
>> How can I be of service?                                                                                                                                            
<  ['OKAY MAGICVOICE TO ORANGE AT ARE']                                                                                                                                
<< ['MAGICVOICE TELL ME A DAD JOKE']                                                                                                                                      
DadIntent 0.48913043478260876
ERROR:naomi.conversation:Failed to execute module
Traceback (most recent call last):
  File "/home/pi/.config/naomi/plugins/speechhandler/Dad_Jokes/__init__.py", line 47, in handle
    jokedata = json.loads(jsondoc)
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>> I'm sorry. I had some trouble with that operation. Please try again later.  
```
I'm not sure what the problem is, though.

**Comment by AustinCasteel** [comment]
I see the issue. I am not passing the json header so it is returning the joke as html which then json can't parse to get said joke.

**Review by aaronchantrill — CHANGES_REQUESTED** [review]
Okay, the plugin works now when I pulled the latest version. It looks like you just need to update the commit from a9fd5dc to ca358fa in plugins.csv.
```
>> My name is MAGICVOICE.                                                      
>> How can I be of service?                                                    
<  ['THE MAGICVOICE ONE UH THAT SHOW']                                         
<< ['MAGICVOICE TELL ME DAD JOKE']                                               
DadIntent 0.8405797101449275
>> Why did the A go to the bathroom and come out as an E? Because he had a vowel movement.
```
Thanks!

**Comment by AustinCasteel** [comment]
Oops, forgot about updating the commit. Should be good to go now.

**Review by aaronchantrill — APPROVED** [review]
Okay, cool. After a `Naomi --remove "Dad Jokes"` and `Naomi --install "Dad Jokes"` I got:
```
>> My name is MAGICVOICE.                                                                                                                                              
>> How can I be of service?                                                                                                                                            
<  ['MAGICVOICE TO ENOUGH YOUR']                                                                                                               
<< ['MAGICVOICE TELL YOU DAD JOKE']                                                                                                       
DadIntent 1.196784420289855
>> I fear for the calendar, its days are numbered.
```
If you are ready, I will go ahead and merge these in

**Pull request merged**
